collections:
  - name: amazon.aws
    version: 6.0.0
  - name: azure.azcollection
    version: 1.18.1
  - name: community.general
    version: 7.4.0
  - name: community.rabbitmq
    version: 1.2.3
  - name: google.cloud
    version: 1.2.0
